project_name: accord
builds:
  - binary: accord-server
    dir: cmd/accord-server
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      386: i386
      amd64: x86_64
dockers:
  - goarch: amd64
    image_templates:
      - blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - goarch: arm64
    image_templates:
      - blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "blacksquaremedia/accord:latest"
    image_templates:
      - "blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "blacksquaremedia/accord:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: "checksums.txt"
changelog:
  skip: true
