# Default values for accord.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: "blacksquaremedia/accord"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  type: NodePort
  port: 7475

secrets: ""
# The of a  kubernetes secrets map that contains a database URL in the form
# postgres://user:pass@host:port/database

volumes:
  - name: ephemeral
    emptyDir: {}

volumeMounts:
  - name: ephemeral
    mountPath: "/tmp"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
